### PR TITLE
Allow to specify the output file for backups

### LINKED ISSUE #10: Allow to specify the folder for backups and restores
It would be nice is user could select the folder where backups are saved and the full path of the file (s)he would like to restore.

### PR DESCRIPTION
**Pull request by Phyks**
Adds an optional backup file parameter to specify the file to save backups to. Closes #10.

I tried to keep code style coherent with the rest of the code, let me know if everything is not ok.

### CODE REVIEW

**Comment by nono** [comment]
@nledez @aeris can you look at this PR please?

**Comment by clochix** [comment]
Another user is requesting this feature, could we do something?

**Comment by jsilvestre** [comment]
Hi @Phyks, sorry for the late answer. We've taken into account the PR and will work on it as soon as possible.

We'll try to get back at you sooner next time!

**Comment by Phyks** [comment]
Any news on this? :)

**Comment by aeris** [comment]
I work on this commit this day.
Already integrated on our dev env for testing and will be shipped on the next release (perhaps next week).

**Comment by Phyks** [comment]
Ok, thanks!

**Comment by aeris** [comment]
Merged and tested on 1905ab0fb7f9988fc131656153ab18382e880997 !

**Pull request closed without merging**
